# Generated by Django 5.2.6 on 2026-03-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='slug',
            field=models.SlugField(default='sluggy', unique=True),
            preserve_default=False,
        ),
    ]
